title = "智能化开发文档"

theme = "docPort"

baseURL = 'http://127.0.0.1/'

languageCode = 'zh-CN'
defaultContentLanguage = "zh"
pygmentsCodeFences = true
pygmentsStyle = "monokai"

defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false
uglyurls = true


disableKinds = ["taxonomy", "taxonomyTerm", "category", "RSS"]

# Keep this as is
[outputs]
	home = [ "HTML", "RSS", "JSON"]

# Site params
[params]
	ordersectionsby = "weight" # ordersectionsby = "title"
	color_main = "#737373"
	color_second = "#b30000"
	disableSearch = false # default is false
	disableNavChevron = false # set true to hide next/prev chevron, default is false
	menushortcutsnewtab = false # set true to open shortcuts links to a new tab/window

[markup.goldmark.renderer]
	unsafe = true

# 代码高亮配置
[markup.highlight]
	anchorLineNos = true
	codeFences = true
	guessSyntax = true
	hl_Lines = ""
	hl_inline = false
	lineNoStart = 1
	lineNos = true
	lineNumbersInTable = false
	noClasses = true
	style = "monokai"
	tabWidth = 2

#
# top menu shotcuts
#
[[menu.shortcuts]]
name = "Github"
identifier = "ds"
url = "https://github.com/vjeantet/hugo-theme-docport"
weight = 10

[[menu.shortcuts]]
name = "Download"
url = "https://github.com/vjeantet/hugo-theme-docport/archive/master.zip"
weight = 11

[[menu.shortcuts]]
name = "Hugo Documentation"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20

[[menu.shortcuts]]
name = "关于"
url = "/docport-theme/credits/"
weight = 30